[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
edition = "2024"
version = "0.1.0"

[workspace.dependencies]
chrono = { version = "0.4", default-features = false, features = ["std"] }
regex = "1"
serde = { version = "1", features = ["derive"] }
saphyr = "0.1"
clap = { version = "4", features = ["derive"] }
clap_complete = "4"
